---
# Source: nfs-client-provisioner/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.11
    heritage: Helm
    release: csi-nfs-hdd
  name: run-csi-nfs-hdd
subjects:
  - kind: ServiceAccount
    name: csi-nfs-hdd
    namespace: csi-nfs-hdd
roleRef:
  kind: ClusterRole
  name: csi-nfs-hdd-runner
  apiGroup: rbac.authorization.k8s.io
