apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-tages.dev
spec:
  acme:
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-dns-tages.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
        - tages.dev
      dns01:
        route53:
          region: eu-central-1
          accessKeyID: AKIATXMGCZP7GEYZJD4P
          secretAccessKeySecretRef:
            name: access-route53
            key: access-key
