apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tages.dev
  namespace: istio-system
spec:
  dnsNames:
  - tages.dev
  - "*.tages.dev"
  secretName: cert-tages.dev
  issuerRef:
    name: letsencrypt-dns-tages.dev
    kind: ClusterIssuer
