---
# Source: promtail/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-promtail-clusterrolebinding
  labels:
    app: promtail
    chart: promtail-2.2.0
    release: logging-promtail
    heritage: Helm
subjects:
  - kind: ServiceAccount
    name: logging-promtail
    namespace: logging
roleRef:
  kind: ClusterRole
  name: logging-promtail-clusterrole
  apiGroup: rbac.authorization.k8s.io
