---
# Source: promtail/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logging-promtail
  namespace: logging
  labels:
    app: promtail
    chart: promtail-2.2.0
    heritage: Helm
    release: logging-promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logging-promtail
subjects:
- kind: ServiceAccount
  name: logging-promtail
