{{ $host := "prometheus-monitoring.tages.dev" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $host }}
spec:
  gateways:
  - istio-system/tages-dev-443
  hosts:
  - {{ $host }}
  http:
  - route:
    - destination:
        host: prometheus-k8s
        port:
          number: 9090
