persistence:
  enabled: true
  size: 1Gi
  storageClassName: nfs-hdd
config:
  chunk_store_config:
    max_look_back_period: 336h
  table_manager:
    retention_deletes_enabled: true
    retention_period: 336h
