---
# Source: loki/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logging-loki
  namespace: logging
  labels:
    app: loki
    chart: loki-2.3.0
    heritage: Helm
    release: logging-loki
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logging-loki
subjects:
- kind: ServiceAccount
  name: logging-loki
