---
# Source: loki/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: logging-loki
  namespace: logging
  labels:
    app: loki
    chart: loki-2.3.0
    release: logging-loki
    heritage: Helm
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: loki
    release: logging-loki
