---
# Source: loki/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: loki
    chart: loki-2.3.0
    heritage: Helm
    release: logging-loki
  annotations:
    {}
  name: logging-loki
  namespace: logging
