apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: "{\"auths\":{\"registry.tjump.ru:5000\":{\"username\":\"gitlab\",\"password\":\"w6MJivvKhKeyNs4WdYb\"}}}"
