apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shell-operator
rules:
- apiGroups:
  - "*"
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "*"
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - "*"
