apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: 80to443
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      number: 80
      name: HTTP
      protocol: HTTP
    tls:
      httpsRedirect: true
