---
# Source: grafana/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-grafana-clusterrolebinding
  labels:
    helm.sh/chart: grafana-5.7.10
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: logging-grafana
    app.kubernetes.io/version: "7.2.1"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: logging-grafana
    namespace: logging
roleRef:
  kind: ClusterRole
  name: logging-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
