---
# Source: grafana/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    helm.sh/chart: grafana-5.7.10
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: logging-grafana
    app.kubernetes.io/version: "7.2.1"
    app.kubernetes.io/managed-by: Helm
  name: logging-grafana-clusterrole
rules: []
