---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-grafana
  namespace: logging
  labels:
    helm.sh/chart: grafana-5.7.10
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: logging-grafana
    app.kubernetes.io/version: "7.2.1"
    app.kubernetes.io/managed-by: Helm
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Loki
      type: loki
      url: http://logging-loki:3100
      version: 1
