---
# Source: grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: logging-grafana
  namespace: logging
  labels:
    helm.sh/chart: grafana-5.7.10
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: logging-grafana
    app.kubernetes.io/version: "7.2.1"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [logging-grafana]
